#!/bin/bash

set -e
set -o pipefail

APPNAME=mani
PROJECT_DIR=$(dirname "$(cd "$(dirname "${0}")"; pwd -P)")

function build_docker_images() {
  for dockerfile in `ls ${PROJECT_DIR}/test/images/*.test.Dockerfile`; do
    testcase=`basename ${dockerfile} | sed -e s/\.test\.Dockerfile$//`
    echo "┌───────────── ${testcase}"
    echo "│ [Docker] Building image..."

    docker build                        \
      --file ${dockerfile}              \
      --tag ${APPNAME}/test:${testcase} \
      --build-arg USER_ID=$(id -u)      \
      . |                               \
      sed "s/^/│ /"
    echo "└───────────── ${testcase} [OK]"

    echo '----------------------'
    echo $testcase
    echo "${APPNAME}/test:${testcase}"
    echo '----------------------'
  done
}

function __main__() {
  build_docker_images
}

__main__ $@
