#!/bin/bash

set -e
set -o pipefail

APPNAME=mani
PROJECT_DIR=$(dirname "$(cd "$(dirname "${0}")"; pwd -P)")

function help() {
  cat >&2 << EOF
This script is a driver for "runtime tests".
The "runtime test" is to test this package in specific environments,
defined by Dockerfiles.

Options:
  --test|-t {case}     Run only cases which have specified pattern in the case names.
  --help|-h           Show this message

Examples:

  ./test/run.sh

EOF
}

function parse_options() {
  RUN=
  UPDATE_GOLDEN=
  DIRTY=
  VERBOSE=
  UPDATE=
  while [[ $# -gt 0 ]]; do
  case "${1}" in
      --verbose|-d)
      VERBOSE=YES
      shift
      ;;
      --dirty|-f)
      DIRTY=YES
      shift
      ;;
      --run|-t)
      RUN="${2}"
      shift && shift
      ;;
      --update-golden|-u)
      UPDATE_GOLDEN=YES
      shift && shift
      ;;
      --help|-h)
      help && exit 0
      ;;
      *)
      printf "Unkown flag: ${1}\n\n"
      help
      exit 1
      ;;
  esac
  done
}

function run_tests() {
  for runtime in `ls ${PROJECT_DIR}/test/images/*.Dockerfile`; do
    testcase=`basename ${runtime} | sed -e s/\.Dockerfile$//`
    echo ${APPNAME}/test:${testcase}

    echo "┌───────────── ${testcase}"
    echo "│ [Docker] Running tests..."
    docker run -it --rm --volume pwd:/opt ${APPNAME}/test:${testcase} /bin/sh -c "go test ./... -v" | \
      sed "s/^/│ [${testcase}] /"
    # docker run -it --rm --volume pwd:/opt ${APPNAME}/test:${testcase} "/usr/local/go/ version"
    echo "└───────────── ${testcase} [OK]"

    # docker run -i -t -e "TESTCASE=${testcase}" --rm ${APPNAME}/test:${testcase} | sed "s/^/│ [${testcase}] /"
  done
}

function __main__() {
  parse_options $@
  run_tests
}

__main__ $@
