#!/bin/bash

set -e
set -o pipefail

APPNAME=mani
PROJECT_DIR=$(dirname "$(cd "$(dirname "${0}")"; pwd -P)")

function help() {
  cat >&2 << EOF
This script is a driver for "runtime tests".
The "runtime test" is to test this package in specific environments,
defined by Dockerfiles.

Options:
  --test|-t {case}     Run only cases which have specified pattern in the case names.
  --help|-h           Show this message

Examples:

  ./test/run.sh

EOF
}

function parse_options() {
  RUN=
  UPDATE_GOLDEN=
  DIRTY=
  DEBUG=
  while [[ $# -gt 0 ]]; do
  case "${1}" in
      --debug|-d)
      DEBUG="-debug"
      shift
      ;;
      --dirty|-f)
      DIRTY="-dirty"
      shift
      ;;
      --update-golden|-u)
      UPDATE_GOLDEN="-update"
      shift
      ;;
      --run|-t)
      RUN="-run=${2}"
      shift && shift
      ;;
      --help|-h)
      help && exit 0
      ;;
      *)
      printf "Unkown flag: ${1}\n\n"
      help
      exit 1
      ;;
  esac
  done
}

function run_tests() {
  for runtime in `ls ${PROJECT_DIR}/test/images/*.Dockerfile`; do
    testcase=`basename ${runtime} | sed -e s/\.Dockerfile$//`
    echo ${APPNAME}/test:${testcase}

    echo "┌───────────── ${testcase}"
    echo "│ [Docker] Running tests..."
    # docker run -it --rm --volume $PWD:/opt ${APPNAME}/test:${testcase}
    docker run                                                          \
      -it --rm                                                          \
      --user "$(id -u):$(id -g)"                                        \
      --volume "$PWD:/opt"                                              \
      ${APPNAME}/test:${testcase}                                       \
      /bin/sh -c "go test -v ./... $RUN $DIRTY $DEBUG $UPDATE_GOLDEN" | \
      sed "s/^/│ [${testcase}] /"

    echo "└───────────── ${testcase} [OK]"
  done
}

function __main__() {
  parse_options $@
  run_tests
}

__main__ $@
