name: build

on:
  push:
    branches: [test/add-tests]
  pull_request:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest]
        go: [1.16]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build docker images
        shell: 'script -q -e -c "bash {0}"'
        run: bash ./test/build

      - name: Test
        shell: 'script -q -e -c "bash {0}"'
        run: bash ./test/test --run TestInfoCmd

  # test:
  #   name: test
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macOS-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Set up Go
  #       uses: actions/setup-go@v1
  #       with:
  #         go-version: 1.16
  #     - name: Check out code
  #       uses: actions/checkout@v1
  #     - name: Run Unit tests.
  #       run: make test
